In [1]:
import pandas as pd

In [2]:
def fips_code(x):
    l=[]
    for i in x:
        if i <10:
            l.append("04000US0"+str(i))
        else:
            l.append("04000US"+str(i))
    return l

In [3]:

president=pd.read_csv("https://dataverse.harvard.edu/api/access/datafile/:persistentId?persistentId=doi:10.7910/DVN/42MVDX/MFU99O",delimiter='\t')

In [4]:
president.head()

,year,state,state_po,state_fips,state_cen,state_ic,office,candidate,party,writein,candidatevotes,totalvotes,version,notes
0,1976,Alabama,AL,1,63,41,US President,"Carter, Jimmy",democrat,False,659170,1182850,20171015,NaN
1,1976,Alabama,AL,1,63,41,US President,"Ford, Gerald",republican,False,504070,1182850,20171015,NaN
2,1976,Alabama,AL,1,63,41,US President,"Maddox, Lester",american independent party,False,9198,1182850,20171015,NaN
3,1976,Alabama,AL,1,63,41,US President,"Bubar, Benjamin \\""Ben\""\""""",prohibition,False,6669,1182850,20171015,NaN
4,1976,Alabama,AL,1,63,41,US President,"Hall, Gus",communist party use,False,1954,1182850,20171015,NaN

In [5]:
total=president.isnull().sum().sort_values(ascending=False)
percent=(president.isnull().sum()/president.isnull().count()).sort_values(ascending=False)
pd.concat([total,percent],keys=["Total","Percent"],axis=1)

                Total   Percent
notes            3740  1.000000
party             336  0.089840
candidate         266  0.071123
version             0  0.000000
totalvotes          0  0.000000
candidatevotes      0  0.000000
writein             0  0.000000
office              0  0.000000
state_ic            0  0.000000
state_cen           0  0.000000
state_fips          0  0.000000
state_po            0  0.000000
state               0  0.000000
year                0  0.000000

In [6]:
president[(president['candidate']=='Other')&(president['writein']==True)&(president['party'].isnull())]

,year,state,state_po,state_fips,state_cen,state_ic,office,candidate,party,writein,candidatevotes,totalvotes,version,notes
2414,2004,Alabama,AL,1,63,41,US President,Other,NaN,True,898,1883415,20171015,NaN
2421,2004,Alaska,AK,2,94,81,US President,Other,NaN,True,790,312598,20171015,NaN
2425,2004,Arizona,AZ,4,86,61,US President,Other,NaN,True,2911,2012585,20171015,NaN
2438,2004,California,CA,6,93,71,US President,Other,NaN,True,20854,12421353,20171015,NaN
2483,2004,Georgia,GA,13,58,44,US President,Other,NaN,True,3085,3301875,20171015,NaN
2496,2004,Illinois,IL,17,33,21,US President,Other,NaN,True,4384,5274322,20171015,NaN
2500,2004,Indiana,IN,18,32,22,US President,Other,NaN,True,1495,2468002,20171015,NaN
2507,2004,Iowa,IA,19,42,31,US President,Other,NaN,True,1094,1506908,20171015,NaN
2514,2004,Kansas,KS,20,47,32,US President,Other,NaN,True,47,1187756,20171015,NaN
2520,2004,Kentucky,KY,21,61,51,US President,Other,NaN,True,22,1795882,20171015,NaN
2565,2004,Minnesota,MN,27,41,33,US President,Other,NaN,True,2532,2828387,20171015,NaN
2593,2004,Nebraska,NE,31,46,35,US President,Other,NaN,True,931,778186,20171015,NaN
2605,2004,New Hampshire,NH,33,12,4,US President,Other,NaN,True,965,678287,20171015,NaN
2624,2004,New York,NY,36,21,13,US President,Other,NaN,True,304,7448266,20171015,NaN
2634,2004,North Dakota,ND,38,44,36,US President,Other,NaN,True,9,312833,20171015,NaN
2638,2004,Ohio,OH,39,31,24,US President,Other,NaN,True,358,5627903,20171015,NaN
2677,2004,Tennessee,TN,47,62,54,US President,Other,NaN,True,39,2437319,20171015,NaN
2681,2004,Texas,TX,48,74,49,US President,Other,NaN,True,12341,7410749,20171015,NaN
2689,2004,Utah,UT,49,87,67,US President,Other,NaN,True,43,927844,20171015,NaN
2694,2004,Vermont,VT,50,13,6,US President,Other,NaN,True,957,312309,20171015,NaN
2701,2004,Virginia,VA,51,54,40,US President,Other,NaN,True,2521,3195415,20171015,NaN
2726,2004,Wyoming,WY,56,83,68,US President,Other,NaN,True,480,243861,20171015,NaN
3540,2016,Maryland,MD,24,52,52,US President,Other,NaN,True,10921,2781446,20171015,NaN

In [7]:
president.drop("notes",axis=1,inplace=True)
president['state_fips']=fips_code(president['state_fips'])
president.loc[(president['writein']==True),'candidate']="Other"
president.loc[(president['writein']==True),'party']="Other"
president.loc[(president['party']=="no party affiliation")&(president['candidate'].isnull()),'candidate']="Other"
president.loc[(president['party']=="other")&(president['candidate'].isnull()),'candidate']="Other"
president.loc[(president['party']=="other"),'party']="Other"
president.loc[(president['party']=="unenrolled")&(president['candidate'].isnull()),'candidate']="Other"
president.loc[(president['candidate'].isnull()),'candidate']="Unavailable"
president.loc[((president['party'].isnull())&(president['candidate']=="Other")),'party']="Other"
president.loc[((president['candidate']=="Blank Vote")|(president['candidate']=="Blank Vote/Scattering")|(president['candidate']=="Blank Vote/Scattering/ Void Vote")|(president['candidate']=="Blank Vote/Void Vote/Scattering")|(president['candidate']=="Scattering")|(president['candidate']=="Void Vote")|(president['candidate']=="Over Vote")|(president['candidate']=="None Of The Above")|(president['candidate']=="None Of These Candidates")|(president['candidate']=="Not Designated")),'party']="Unavailable"
president.loc[((president['candidate']=="Blank Vote")|(president['candidate']=="Blank Vote/Scattering")|(president['candidate']=="Blank Vote/Scattering/ Void Vote")|(president['candidate']=="Blank Vote/Void Vote/Scattering")|(president['candidate']=="Scattering")|(president['candidate']=="Void Vote")|(president['candidate']=="Over Vote")|(president['candidate']=="None Of The Above")|(president['candidate']=="None Of These Candidates")|(president['candidate']=="Not Designated")),'candidate']="Blank Vote"

In [8]:
# total=president.isnull().sum().sort_values(ascending=False)
# percent=(president.isnull().sum()/president.isnull().count()).sort_values(ascending=False)
# pd.concat([total,percent],keys=["Total","Percent"],axis=1)

In [9]:
# president[(president['party'].isnull())]
president.shape

(3740, 13)

In [10]:
# president[president['candidate']=="None Of These Candidates"]
# president[president['party']=="unaffiliated"]
president.head()

,year,state,state_po,state_fips,state_cen,state_ic,office,candidate,party,writein,candidatevotes,totalvotes,version
0,1976,Alabama,AL,04000US01,63,41,US President,"Carter, Jimmy",democrat,False,659170,1182850,20171015
1,1976,Alabama,AL,04000US01,63,41,US President,"Ford, Gerald",republican,False,504070,1182850,20171015
2,1976,Alabama,AL,04000US01,63,41,US President,"Maddox, Lester",american independent party,False,9198,1182850,20171015
3,1976,Alabama,AL,04000US01,63,41,US President,"Bubar, Benjamin \\""Ben\""\""""",prohibition,False,6669,1182850,20171015
4,1976,Alabama,AL,04000US01,63,41,US President,"Hall, Gus",communist party use,False,1954,1182850,20171015

In [11]:
temp=president[(president["year"]==2016)&(president['state_po']=="FL")]
# temp.groupby(["candidate"])["totalvotes"].sum()
# j=temp['party'].unique()
x=temp['candidatevotes'].sum()
j=((temp.groupby(["candidate"])['candidatevotes'].sum()/x)*100).sort_values(ascending=False)
# print(x)
j

candidate
Trump, Donald J.                     49.021941
Clinton, Hillary                     47.823316
Johnson, Gary                         2.197900
Stein, Jill                           0.683638
Castle, Darrell L.                    0.174893
De La Fuente, Roque \\"Rocky\"\""     0.096687
Other                                 0.001624
Name: candidatevotes, dtype: float64