In [1]:
from fuzzywuzzy import process
from fuzzywuzzy import fuzz
import collections
import pandas as pd

In [2]:
house=pd.read_csv("https://dataverse.harvard.edu/api/access/datafile/:persistentId?persistentId=doi:10.7910/DVN/IG0UN2/8KAB8V", delimiter='\t')

In [3]:
house_candidate=pd.read_csv("https://cg-519a459a-0ea3-42c2-b7bc-fa1143481f74.s3.us-gov-west-1.amazonaws.com/8bef4b8897fa19c5b0152937d609a4aa1a2d84aea1dd23de15be3160.csv?response-content-disposition=filename%3Dcandidates-2019-07-11T09%3A41%3A22.csv&AWSAccessKeyId=AKIAR7FXZINYMI3G4BRV&Signature=Sh9AF023HAUOjO8Z3zNnNfb6mL8%3D&Expires=1563457289")

In [4]:
house_candidate1=house_candidate.loc[:,["name","party_full","state","district","election_years","candidate_id"]]
house_candidate.head()

,name,office,office_full,party,party_full,state,district,district_number,election_districts,election_years,...,incumbent_challenge,incumbent_challenge_full,load_date,first_file_date,last_file_date,last_f2_date,candidate_id,active_through,candidate_inactive,inactive_election_years
0,"WHITTAKER, RICHARD",H,House,DEM,DEMOCRATIC PARTY,AK,0.0,0.0,{00},{1980},...,NaN,NaN,2002-03-30 00:00:00,1980-06-16,1980-06-16,1980-06-16,H0AK00014,1980,f,NaN
1,"DIERLAM, JESSE HOWELL",H,House,DEM,DEMOCRATIC PARTY,AK,0.0,0.0,{00},{1990},...,C,Challenger,2002-04-02 00:00:00,1989-09-11,1989-09-11,1989-09-11,H0AK00022,1990,f,NaN
2,"SINKOLA, GARY",H,House,REP,REPUBLICAN PARTY,AK,0.0,0.0,{00},{1990},...,C,Challenger,2002-03-30 00:00:00,NaN,NaN,NaN,H0AK00030,1990,f,NaN
3,"YOUNG, ANNA",H,House,GRE,GREEN PARTY,AK,0.0,0.0,{00},{2000},...,C,Challenger,2002-04-07 00:00:00,2000-04-18,2000-04-18,2000-04-18,H0AK00048,2000,f,NaN
4,"GREENE, CLIFFORD MARK",H,House,DEM,DEMOCRATIC PARTY,AK,0.0,0.0,"{00,00}","{2000,2002}",...,C,Challenger,2002-04-07 00:00:00,2000-09-11,2002-07-31,2002-07-31,H0AK00055,2002,f,NaN

In [18]:
total=house.isnull().sum().sort_values(ascending=False)
percent=(house.isnull().sum()/house.isnull().count()).sort_values(ascending=False)
pd.concat([total,percent],keys=["Total","Percent"],axis=1)

                Total  Percent
version             0      0.0
stage               0      0.0
state               0      0.0
state_po            0      0.0
state_fips          0      0.0
state_cen           0      0.0
state_ic            0      0.0
office              0      0.0
district            0      0.0
runoff              0      0.0
unofficial          0      0.0
special             0      0.0
candidate           0      0.0
party               0      0.0
writein             0      0.0
mode                0      0.0
candidatevotes      0      0.0
totalvotes          0      0.0
year                0      0.0

In [6]:
#Sets all null runoff to False
house.loc[(house['runoff'].isnull()), 'runoff']=False

#Sets all null candidates and Parties to Other
house.loc[((house['candidate'].isnull())|(house["candidate"]=="other")), 'candidate']='Other'
house.loc[(house['party'].isnull()), 'party']='Other'
house.loc[((house["candidate"]=="scattering")|(house['candidate']=="scatter")),'candidate']="Scatter"
house.loc[(house["candidate"]=="no name"),'candidate']="Unavailable"

#Sets all of the 2006 Texas stages to general
house.loc[(house['stage'].isnull()), 'stage']='gen'

In [7]:
def eyear(nd):
    l=[]
    for index,row in nd.iterrows():
        i=row.values
        t=i[4]
        j=t.strip('{').strip('}').split(',')
        for x in j:
            l.append([i[0],i[1],i[2],i[3],int(x),i[5]])
    return l

In [8]:
house_candidate1=pd.DataFrame(eyear(house_candidate1))
house_candidate1.columns=["name","party","state","district","year","candidate_id"]
house_candidate1=house_candidate1[(house_candidate1["year"]>=1976)&(house_candidate1["year"]<=2018)]

In [9]:
#Modifciation method
def modify(x):
    sl=x.replace('"','').split(',')
    sl.reverse()
    s=""
    for i in sl:
        s=s+i+" "
    return s.strip()
#subsequent string
def subsequence(s1,s2,m,n):
    b=0
    a=0
    while b<m and a<n:
        if s1[b]==s2[a]:
            b+=1
        a+=1
    return b==m


#first pass on the data matching
def fpass(x,y):
    #x is a list of candidate from fec and y is a list of candidates from mit
    #output will be dictionary
    l=collections.defaultdict(list)
    for i in y:   
    #     if i not in x:
    #         l[i].append("")
    #         continue
        f=0
        for j in x:
# if i is equal to j we append it to the list of the hashmap for the name in the mit data
            if i==j:
                l[i].append(j)
                break
# if they are similar we merge all the possible outcomes and use fuzz ratio technique to find the best match out of it
            elif subsequence(i,j,len(i),len(j)) or subsequence(j,i,len(j),len(i)):
                l[i].append(j)
            else:
                f+=1
        # if it found nowhere in the fec data we add ""(blank string) to the dictionary
        if f>=len(x):
            l[i].append("")
    return l


# final pass
def out(a,x):
    # a is the dictionary of the output from the fpass
    compare=[]
    for key,value in a.items():
# if the length of the dictonary is 1 and contains a null value we use fuzzy wuzzy logic and replace it with the match having atleast 90% similarity
        if len(value)==1:    
            if value[0]=="":
                t=process.extractOne(key,x)
                if t[1]>=90:
                    compare.append([key,t[0]])
                else:
                    compare.append([key,""])
            else:
                compare.append([key,value[0]])
        else:
            s=""
            m=-1
# if there is already a potential match we just loook for the best from the posible match found using the previous logic
            for i in value:
                if fuzz.ratio(key,i)>m and fuzz.ratio(key,i)>=90:
                    m=fuzz.ratio(key,i)
                    s=i
            compare.append([key,s])
    return compare


# creating the final dictionary
def result(b):
    # b is the list of all the canidate match from the prvious outputs
    hm=collections.defaultdict(str)
    for i in b:
        if i[0] not in hm or hm[i[0]]=="":
            hm[i[0]]=i[1]
    return hm

# count the matched and unmatched output
def check(c):
    m=0
    um=0
    nm=0
    for i,j in c.items():
        if i==j:
            m+=1
        elif j=="":
            um+=1
        else:
            nm+=1
    return pd.DataFrame([m,um,nm],index=["Matched_fully","Blank_string","Matched_partially"])

In [10]:
final_l=[]
for year in range(1976,2020,2):
    x=[modify(i).lower() for i in house_candidate1.loc[(house_candidate1["year"]==year),"name"].unique()]
    y=[i.replace('\\','').replace('"','').lower() for i in house.loc[(house["year"]==year),"candidate"].unique()]
    z=fpass(x,y)
    print("fpass done",year)
    final_l=final_l+out(z,x)
    print("spass done",year)
final_compare=result(final_l)
check(final_compare).head()

fpass done 1976
spass done 1976
fpass done 1978
spass done 1978
fpass done 1980
spass done 1980
fpass done 1982
spass done 1982
fpass done 1984
spass done 1984
fpass done 1986
spass done 1986
fpass done 1988
spass done 1988
fpass done 1990
spass done 1990
fpass done 1992
spass done 1992
fpass done 1994
spass done 1994
fpass done 1996
spass done 1996
fpass done 1998
spass done 1998
fpass done 2000
spass done 2000
fpass done 2002
spass done 2002
fpass done 2004
spass done 2004
fpass done 2006
spass done 2006
fpass done 2008
spass done 2008
fpass done 2010
spass done 2010
fpass done 2012
spass done 2012
fpass done 2014
spass done 2014
fpass done 2016
spass done 2016
fpass done 2018
spass done 2018

                      0
Matched_fully      5443
Blank_string       2714
Matched_partially  6855

In [11]:
final_compare["unavailable"]

''

In [12]:
#Merges all insignificant candidates for my pleasure... (Done by the percentage of votes recieved and name matching)
#C is the list of candidates
#df is the main dataframe
def merge_insig(d, df):
    keep=[]
    other=[]
    for candidate in d.keys():
        if(d[candidate]==''):
            kept=False
            if candidate == 'other':
                other.append(candidate)
                kept=True
            else:
                location= df.loc[(df['candidate'].str.lower()==candidate)]
                byyear = location.groupby('year')
                cvote = byyear.sum()['candidatevotes']
                tvote = byyear.sum()['totalvotes']
                for year in cvote.index:
                    percentage = cvote[year]/tvote[year]*100
                    if percentage > 5:
                        keep.append(candidate)
                        kept=True
                        break
            if kept==False:
                other.append(candidate)
                df.loc[(df['candidate'].str.lower()==candidate), 'candidate']='Other'
    return (keep, other)

In [13]:
merge=merge_insig(final_compare,house)
# print(merge)

In [14]:
hm=collections.defaultdict(str)
for i in house_candidate['name'].values:
    t=house_candidate.loc[(house_candidate['name']==i),'candidate_id'].values
    hm[modify(i).lower()]=t[0]

In [21]:
id_list=[]
for i in house['candidate'].values:
    t=i.replace('\\','').replace('"','').replace(',','').lower()
    if t in ['scatter','blank vote','other','unavailable']:
        id_list.append("P99999999")
    elif t in final_compare:
        if final_compare[t]=="":
            id_list.append("P99999999")
        else:
            id_list.append(hm[final_compare[t]])
    else:
        id_list.append("P99999999")
house["candidate_id"]=id_list

In [22]:
house.head()

,year,state,state_po,state_fips,state_cen,state_ic,office,district,stage,runoff,special,candidate,party,writein,mode,candidatevotes,totalvotes,unofficial,version,candidate_id
0,1976,Alabama,AL,1,63,41,US House,1,gen,False,False,Bill Davenport,democrat,False,total,58906,157170,False,20171005,P99999999
1,1976,Alabama,AL,1,63,41,US House,1,gen,False,False,Jack Edwards,republican,False,total,98257,157170,False,20171005,H6AL01011
2,1976,Alabama,AL,1,63,41,US House,1,gen,False,False,Other,Other,True,total,7,157170,False,20171005,P99999999
3,1976,Alabama,AL,1,63,41,US House,2,gen,False,False,J. Carole Keahey,democrat,False,total,66288,156362,False,20171005,P99999999
4,1976,Alabama,AL,1,63,41,US House,2,gen,False,False,Other,Other,True,total,5,156362,False,20171005,P99999999

In [23]:
final=pd.DataFrame(list(final_compare.items()),columns=["MIT data","FEC data"])
final.head()

                    MIT data                     FEC data
0             bill davenport
1               jack edwards  william jackson iii edwards
2                      other
3           j. carole keahey
4  william l. bill dickinson

In [24]:
final.to_csv("MIT_fec_house_86%CI.csv")

In [25]:
house.to_csv("House_election_1976-2016.csv")